/**
 * Legal source registry.
 *
 * Every legal rule the product applies, and every source a generated document
 * cites, is registered here — separately from model prompts. The registry is
 * versioned in git; changing a source is a reviewed code change.
 *
 * Hierarchy (highest authority first):
 *   1. legislation.gov.uk   2. GOV.UK   3. Acas   4. HMCTS / tribunal procedure
 *   5. curated case law      6. secondary (only where explicitly labelled)
 *
 * The registry distinguishes the NEWEST source from the source LEGALLY
 * APPLICABLE to the user's event: `applicableSources(key, eventDate)` picks the
 * version whose [effectiveFrom, effectiveTo] window contains the event date.
 */

import { ERA_2025, TIME_LIMIT_CONFIG } from "@/legal/era-2025";
import { isRuleCommenced, REGISTER_SESSION } from "@/legal/rules/register";

export type SourceType = "legislation" | "govuk" | "acas" | "hmcts" | "case_law" | "secondary";
export type SourceJurisdiction = "england_wales" | "scotland" | "northern_ireland" | "great_britain" | "uk";
/**
 * Evidential strength for COMMENCEMENT purposes. A gov.uk policy timetable is
 * `secondary` even though GOV.UK ranks second in the citation hierarchy: it can
 * announce a date but cannot commence a provision.
 */
export type SourceStrength = "primary" | "secondary";
export type SourceVerificationMethod = "fetched" | "not_rechecked" | "unreachable" | "not_attempted";

export interface SourceVerification {
    method: SourceVerificationMethod;
    /** The URL actually requested (may differ from `url`, e.g. a /data.xml endpoint). null if not attempted. */
    retrievedFrom: string | null;
    /** ISO datetime of the attempt. null if not attempted. */
    attemptedAt: string | null;
    note?: string;
}

export interface LegalSource {
    key: string;
    title: string;
    publisher: string;
    url: string;
    reference: string;
    jurisdiction: SourceJurisdiction[];
    sourceType: SourceType;
    strength?: SourceStrength;
    publishedDate?: string;
    effectiveFrom: string;
    /** null = still in force */
    effectiveTo: string | null;
    /**
     * Date the source was last actually read by a reviewer. null = never read
     * (a lead or an instrument that could not be retrieved). Only set to today's
     * date for a source fetched today; otherwise keep the prior date and mark
     * `verification.method: "not_rechecked"`.
     */
    lastVerifiedAt: string | null;
    verification: SourceVerification;
    supersededBy?: string;
    /** Free-form applicability notes shown to the user when the source is cited. */
    applicability: string[];
    /** Whether the exact commencement is confirmed by Statutory Instrument (derived from the register where applicable). */
    commencementConfirmed?: boolean;
    version: string;
}

/** The review at which the long-standing sources were last read. */
const PRIOR_REVIEW = "2026-09-24";
/** Not re-fetched in the 26/27 September 2026 session (egress blocked). */
const NOT_RECHECKED: SourceVerification = {
    method: "not_rechecked",
    retrievedFrom: null,
    attemptedAt: REGISTER_SESSION.retrievedAt,
    note: "Retrieval attempted 2026-09-27 but the egress proxy refused the host; prior review date retained.",
};
/** Attempted this session; host refused. Nothing may be claimed as read. */
const UNREACHABLE = (retrievedFrom: string, note?: string): SourceVerification => ({
    method: "unreachable",
    retrievedFrom,
    attemptedAt: REGISTER_SESSION.retrievedAt,
    note: note ?? "HTTP CONNECT refused (403) by the egress proxy; WebFetch reported EGRESS_BLOCKED.",
});
const GOVUK_TIMETABLE_URL = "https://www.gov.uk/government/publications/implementing-the-plan-to-make-work-pay-and-employment-rights-act/plan-to-make-work-pay-and-employment-rights-act-timeline-update";

export const LEGAL_SOURCES: LegalSource[] = [
    {
        key: "era1996_s111",
        title: "Employment Rights Act 1996, section 111 (unfair dismissal: time limit)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/111",
        reference: "ERA 1996 s111(2)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Complaint must be presented before the end of three months beginning with the effective date of termination, or such further period as the tribunal considers reasonable where it was not reasonably practicable to present it in time."],
        version: "1",
    },
    {
        key: "era1996_s207b",
        title: "Employment Rights Act 1996, section 207B (extension of time limits to facilitate conciliation)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/207B",
        reference: "ERA 1996 s207B",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2014-04-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Day A to Day B is not counted; if the limit would expire between Day A and one month after Day B, it expires one month after Day B instead.", "Conciliation started after the limit has already expired does not revive it."],
        version: "1",
    },
    {
        key: "era1996_s108",
        title: "Employment Rights Act 1996, section 108 (qualifying period of employment)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/108",
        reference: "ERA 1996 s108",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2012-04-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Two years' continuous employment for ordinary unfair dismissal (dismissals with an EDT before the ERA 2025 commencement).", "No qualifying period for automatically unfair reasons."],
        version: "1",
    },
    {
        key: "era1996_s23",
        title: "Employment Rights Act 1996, section 23 (unauthorised deductions: complaints to tribunal)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/23",
        reference: "ERA 1996 s23(2)-(4)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Three months beginning with the date of payment of the wages from which the deduction was made, or the last deduction in a series."],
        version: "1",
    },
    {
        key: "era1996_s164",
        title: "Employment Rights Act 1996, section 164 (redundancy payment: claims)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/164",
        reference: "ERA 1996 s164",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Six months beginning with the relevant date, subject to the steps listed in s164(1)."],
        version: "1",
    },
    {
        key: "ea2010_s123",
        title: "Equality Act 2010, section 123 (time limits for work cases)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/123",
        reference: "EA 2010 s123",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Three months starting with the date of the act complained of, or such other period as the tribunal thinks just and equitable.", "Conduct extending over a period is treated as done at the end of the period (s123(3)(a))."],
        version: "1",
    },
    {
        key: "ea2010_s129",
        title: "Equality Act 2010, section 129 (equality of terms: time limits)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/129",
        reference: "EA 2010 s129",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Standard case: six months beginning with the last day of employment."],
        version: "1",
    },
    {
        key: "era1996_part_iva",
        title: "Employment Rights Act 1996, Part IVA (protected disclosures) and section 48 (detriment complaints)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/part/IVA",
        reference: "ERA 1996 ss43A-43L, s47B, s48",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1999-07-02",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Detriment complaints: three months beginning with the date of the act or failure to act (s48(3))."],
        version: "1",
    },
    {
        key: "et_extension_of_jurisdiction_1994",
        title: "Employment Tribunals Extension of Jurisdiction (England and Wales) Order 1994, article 7",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/1994/1623/article/7/made",
        reference: "SI 1994/1623 art 7",
        jurisdiction: ["england_wales"],
        sourceType: "legislation",
        effectiveFrom: "1994-07-12",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Breach of contract claims in the tribunal: three months beginning with the effective date of termination; damages capped at £25,000."],
        version: "1",
    },
    {
        key: "et_extension_of_jurisdiction_scotland_1994",
        title: "Employment Tribunals Extension of Jurisdiction (Scotland) Order 1994, article 7",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/1994/1624/article/7/made",
        reference: "SI 1994/1624 art 7",
        jurisdiction: ["scotland"],
        sourceType: "legislation",
        effectiveFrom: "1994-07-12",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Breach of contract claims in the tribunal in Scotland: three months beginning with the effective date of termination; damages capped at £25,000."],
        version: "1",
    },
    {
        key: "era2025_act",
        title: "Employment Rights Act 2025 (2025 c. 36)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2025/36/contents",
        reference: "2025 c. 36 (Royal Assent 18 December 2025)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        publishedDate: ERA_2025.ROYAL_ASSENT,
        effectiveFrom: ERA_2025.ROYAL_ASSENT,
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/ukpga/2025/36/contents", "Chapter number corroborated only by search-index titles ('Employment Rights Act 2025 Chapter 36' explanatory notes). Act text not read."),
        applicability: ["Parent Act. Most provisions commence by regulations made under it; see the commencement instruments registered below and src/legal/rules/register.ts."],
        version: "1",
    },
    {
        key: "era2025_time_limits",
        title: "Employment Rights Act 2025 — extension of tribunal time limits to six months (reported: s152 and Sch 12)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2025/36/contents",
        reference: "ERA 2025 s152 and Sch 12 (section/schedule numbers from secondary sources; not verified against the Act); commencement by regulations (instrument not yet verified)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        publishedDate: ERA_2025.ROYAL_ASSENT,
        effectiveFrom: TIME_LIMIT_CONFIG.COMMENCEMENT_DATE,
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/ukpga/2025/36/contents", "Search snippets report Sch 12 paragraphs 'in force by S.I. 2026/954 reg. 3'; that instrument was not located or read."),
        applicability: ["Extends the three-month limit to six months for acts on or after commencement (reported 1 October 2026; Scottish contract claims reported 9 November 2026 by separate instrument).", "Exact commencement date to be confirmed by Statutory Instrument; until an instrument is recorded in the register the shorter limit is treated as operative."],
        commencementConfirmed: TIME_LIMIT_CONFIG.TIME_LIMIT_SI_CONFIRMED,
        version: "2",
    },
    {
        key: "era2025_qualifying_period",
        title: "Employment Rights Act 2025 — unfair dismissal qualifying period reduced to six months (s25 and Sch 3)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2025/36/section/25",
        reference: "ERA 2025 s25, Sch 3; commencement reported by SI 2026/559 (not read)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        publishedDate: ERA_2025.ROYAL_ASSENT,
        effectiveFrom: ERA_2025.QUALIFYING_PERIOD_6_MONTHS,
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/uksi/2026/559/made"),
        applicability: ["Reported to apply to dismissals with an effective date of termination on or after 1 January 2027 (SI 2026/559, not yet read). Transitional text unverified."],
        commencementConfirmed: isRuleCommenced("QUALIFYING_PERIOD_6_MONTHS"),
        version: "2",
    },
    // ── ERA 2025 commencement instruments (F08) ─────────────────────────
    {
        key: "era2025_commencement_no1_2026",
        title: "The Employment Rights Act 2025 (Commencement No. 1 and Transitional and Saving Provisions) Regulations 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2026/3/made",
        reference: "SI 2026/3",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: "2026-01-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Commenced provisions on 6 January, 18 February and 6 April 2026 (trade union ballot changes, industrial-action dismissal, SSP day one, parental/paternity day-one rights, sexual harassment as a protected disclosure, 180-day collective-redundancy period)."],
        version: "1",
    },
    {
        key: "era2025_commencement_no2_amendment_2026",
        title: "The Employment Rights Act 2025 (Commencement No. 2 and Transitional and Saving Provisions) (Amendment) Regulations 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2026/323/made",
        reference: "SI 2026/323 (the No. 2 Regulations it amends were not identified)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: "2026-04-06",
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/uksi/2026/323/made"),
        applicability: ["Located by search index only; content not read. Recorded so the stale-source check tracks it."],
        version: "1",
    },
    {
        key: "era2025_commencement_no3_2026",
        title: "The Employment Rights Act 2025 (Commencement No. 3 and Transitional Provisions) Regulations 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2026/373/made",
        reference: "SI 2026/373 (C. 33)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: "2026-04-06",
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/uksi/2026/373/made"),
        applicability: ["Reported: transitional provision for employees serving SSP waiting days before 6 April 2026. Content not read."],
        version: "1",
    },
    {
        key: "era2025_commencement_no4_2026",
        title: "The Employment Rights Act 2025 (Commencement No. 4 and Transitional and Saving Provisions) Regulations 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2026/559/made",
        reference: "SI 2026/559",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: "2026-07-01",
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/uksi/2026/559/made"),
        applicability: ["Reported (search-index snippet of the explanatory note): commences s25 and Sch 3 (unfair dismissal), Sch 3 para 5 on 1 July 2026 and the remainder on 1 January 2027. Content not read; transitional rule unverified."],
        version: "1",
    },
    {
        key: "et_extension_of_time_limits_regs_2026",
        title: "The Employment Tribunal (Extension of Time Limits) (Miscellaneous Amendments and Transitional Provisions) Regulations 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukdsi/2026/9780348282849",
        reference: "Draft ISBN 9780348282849; reported made as SI 2026/758 (number from a search snippet, unverified)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: TIME_LIMIT_CONFIG.COMMENCEMENT_DATE,
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/ukdsi/2026/9780348282849", "Approved by both Houses (reported: Commons 1 July 2026). Reported to amend seven SIs (part-time workers, fixed-term employees, zero-hours, ICE representatives, blacklists, NHS protections) — NOT ERA 1996 or EA 2010 — and to come into force 1 October 2026 with reg 10 transitional (act or failure on or after 1 October 2026; series → last act)."),
        applicability: ["Not relied on by the engine for any modelled family; registered because it fixes the secondary-legislation time limits and its transitional wording is the best available indication of the intended boundary."],
        version: "1",
    },
    {
        key: "et_extension_of_jurisdiction_ew_amendment_2026",
        title: "The Employment Tribunals Extension of Jurisdiction (England and Wales) (Amendment) Order 2026",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukdsi/2026/9780348282832",
        reference: "Draft ISBN 9780348282832; reported made as SI 2026/759 (number from a search snippet, unverified)",
        jurisdiction: ["england_wales"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: TIME_LIMIT_CONFIG.COMMENCEMENT_DATE,
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/ukdsi/2026/9780348282832", "Reported: extends the art 7 limit to six months, in force 1 October 2026, England and Wales only; Scottish Order is for the Scottish Ministers."),
        applicability: ["Breach of contract claims in England and Wales with an EDT on or after 1 October 2026 (reported). Not verified; the three-month rule leads until the made Order is read."],
        commencementConfirmed: isRuleCommenced("boc_ew_6m_era2025"),
        version: "1",
    },
    {
        key: "ec_rules_2014",
        title: "The Employment Tribunals (Early Conciliation: Exemptions and Rules of Procedure) Regulations 2014, Schedule (Early Conciliation Rules of Procedure), rule 9",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2014/254/schedule/made",
        reference: "SI 2014/254, Sch, r 9",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        strength: "primary",
        effectiveFrom: "2014-04-06",
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE("https://www.legislation.gov.uk/uksi/2014/254/schedule/made", "Operative wording NOT quoted from the instrument. Search snippet paraphrase: Acas must send the certificate by email where an email address was given, otherwise by post; a certificate sent by email is treated as received on the day it is sent. Verify before encoding."),
        applicability: ["Governs when the early conciliation certificate is treated as received, which fixes Day B under ERA 1996 s207B."],
        version: "1",
    },
    {
        key: "govuk_era2025_timetable",
        title: "GOV.UK — Implementing the Plan to Make Work Pay and Employment Rights Act: timeline update",
        publisher: "GOV.UK (Department for Business and Trade)",
        url: GOVUK_TIMETABLE_URL,
        reference: "Policy timetable (reported updated 25 September 2026); subject to parliamentary process",
        jurisdiction: ["great_britain"],
        sourceType: "govuk",
        strength: "secondary",
        effectiveFrom: "2026-07-16",
        effectiveTo: null,
        lastVerifiedAt: null,
        verification: UNREACHABLE(GOVUK_TIMETABLE_URL, "Page not retrievable (gov.uk blocked; api/content endpoint also blocked). Dates below are as relayed by search snippets of secondary commentary: time limits 1 Oct 2026; Scottish contract claims 9 Nov 2026; harassment (all reasonable steps, third party) 30 Oct 2026; duty to inform of right to join a union 1 Jan 2027; NDAs 2027 (no day); qualifying period, compensatory award, fire and rehire 1 Jan 2027."),
        applicability: ["A statement of intended dates. It cannot commence a provision and is never used to confirm a rule; it is recorded so divergences from the register are visible and tracked."],
        version: "2026-09-25",
    },
    {
        key: "acas_code_2015",
        title: "Acas Code of Practice on disciplinary and grievance procedures (2015)",
        publisher: "Acas",
        url: "https://www.acas.org.uk/acas-code-of-practice-on-disciplinary-and-grievance-procedures",
        reference: "Acas Code of Practice 1 (2015)",
        jurisdiction: ["great_britain"],
        sourceType: "acas",
        publishedDate: "2015-03-11",
        effectiveFrom: "2015-03-11",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Sets the minimum fair process for disciplinary and grievance procedures.", "Tribunals may adjust compensation by up to 25% for unreasonable failure to follow it (TULRCA 1992 s207A)."],
        version: "2015",
    },
    {
        key: "acas_early_conciliation_guidance",
        title: "Acas — Early conciliation",
        publisher: "Acas",
        url: "https://www.acas.org.uk/early-conciliation",
        reference: "Acas early conciliation guidance",
        jurisdiction: ["great_britain"],
        sourceType: "acas",
        effectiveFrom: "2014-04-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Most tribunal claims require an Acas early conciliation certificate before the claim can be presented."],
        version: "1",
    },
    {
        key: "et_rules_2024",
        title: "Employment Tribunal Procedure Rules 2024",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/uksi/2024/1155/contents/made",
        reference: "SI 2024/1155",
        jurisdiction: ["great_britain"],
        sourceType: "hmcts",
        publishedDate: "2024-11-11",
        effectiveFrom: "2025-01-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Replaced the 2013 Rules from 6 January 2025. Cite these rules, never the 2013 rules."],
        version: "2024",
    },
    {
        key: "govuk_et1",
        title: "GOV.UK — Make a claim to an employment tribunal",
        publisher: "GOV.UK",
        url: "https://www.gov.uk/employment-tribunals/make-a-claim",
        reference: "GOV.UK employment tribunals guidance",
        jurisdiction: ["great_britain"],
        sourceType: "govuk",
        effectiveFrom: "2014-04-06",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Official route for completing and submitting the ET1 claim form online."],
        version: "1",
    },
    {
        key: "govuk_bank_holidays",
        title: "GOV.UK — UK bank holidays",
        publisher: "GOV.UK",
        url: "https://www.gov.uk/bank-holidays",
        reference: "GOV.UK bank holidays",
        jurisdiction: ["uk"],
        sourceType: "govuk",
        effectiveFrom: "2000-01-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Used only to warn when a deadline falls on a non-working day. The statutory limit is not extended."],
        version: "1",
    },
    {
        key: "swainston_hetton",
        title: "Swainston v Hetton Victory Club Ltd",
        publisher: "Court of Appeal (curated)",
        url: "https://www.bailii.org/",
        reference: "[1983] ICR 341",
        jurisdiction: ["england_wales"],
        sourceType: "case_law",
        effectiveFrom: "1983-01-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["A time limit expiring on a non-working day is not extended to the next working day."],
        version: "1",
    },
    {
        key: "era1996_s230",
        title: "Employment Rights Act 1996, section 230 (employees, workers etc.)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/230",
        reference: "ERA 1996 s230",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Defines employee (contract of employment) and worker (limb (b))."],
        version: "1",
    },
    {
        key: "era1996_s95",
        title: "Employment Rights Act 1996, section 95 (circumstances in which an employee is dismissed)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/95",
        reference: "ERA 1996 s95",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Dismissal includes termination by the employer, expiry of a limited-term contract, and constructive dismissal (s95(1)(c))."],
        version: "1",
    },
    {
        key: "era1996_s94_98",
        title: "Employment Rights Act 1996, sections 94 and 98 (right not to be unfairly dismissed; fairness)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/98",
        reference: "ERA 1996 ss94, 98",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Employer must show a potentially fair reason (s98(1)-(2)); tribunal decides reasonableness in all the circumstances (s98(4))."],
        version: "1",
    },
    {
        key: "era1996_s86",
        title: "Employment Rights Act 1996, section 86 (rights to minimum notice)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/86",
        reference: "ERA 1996 s86",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Minimum notice: one week after one month's service, rising to one week per year up to twelve weeks."],
        version: "1",
    },
    {
        key: "era1996_s13",
        title: "Employment Rights Act 1996, section 13 (right not to suffer unauthorised deductions)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/1996/18/section/13",
        reference: "ERA 1996 s13",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "1996-08-22",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["A deduction is unlawful unless required by statute, authorised by a written contract term, or agreed in writing in advance."],
        version: "1",
    },
    {
        key: "ea2010_s4",
        title: "Equality Act 2010, section 4 (the protected characteristics)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/4",
        reference: "EA 2010 s4",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Lists the nine protected characteristics."],
        version: "1",
    },
    {
        key: "ea2010_s6",
        title: "Equality Act 2010, section 6 (disability)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/6",
        reference: "EA 2010 s6",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Physical or mental impairment with a substantial and long-term adverse effect on normal day-to-day activities."],
        version: "1",
    },
    {
        key: "ea2010_s13",
        title: "Equality Act 2010, section 13 (direct discrimination)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/13",
        reference: "EA 2010 s13",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Less favourable treatment because of a protected characteristic."],
        version: "1",
    },
    {
        key: "ea2010_s19",
        title: "Equality Act 2010, section 19 (indirect discrimination)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/19",
        reference: "EA 2010 s19",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["A provision, criterion or practice that puts a group and the claimant at a particular disadvantage and is not justified."],
        version: "1",
    },
    {
        key: "ea2010_s20_21",
        title: "Equality Act 2010, sections 20–21 and Schedule 8 (duty to make reasonable adjustments)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/20",
        reference: "EA 2010 ss20-21, Sch 8",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Three requirements: PCPs, physical features, auxiliary aids. No duty if the employer did not know and could not reasonably be expected to know."],
        version: "1",
    },
    {
        key: "ea2010_s23",
        title: "Equality Act 2010, section 23 (comparison by reference to circumstances)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/23",
        reference: "EA 2010 s23",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["No material difference between the circumstances of the claimant and the comparator."],
        version: "1",
    },
    {
        key: "ea2010_s26",
        title: "Equality Act 2010, section 26 (harassment)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/26",
        reference: "EA 2010 s26",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Unwanted conduct related to a protected characteristic with the purpose or effect of violating dignity or creating a hostile environment."],
        version: "1",
    },
    {
        key: "ea2010_s27",
        title: "Equality Act 2010, section 27 (victimisation)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/27",
        reference: "EA 2010 s27",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Detriment because of a protected act."],
        version: "1",
    },
    {
        key: "ea2010_s39",
        title: "Equality Act 2010, section 39 (employees and applicants)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/39",
        reference: "EA 2010 s39",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Prohibits discrimination in recruitment, terms, promotion, dismissal and other detriments."],
        version: "1",
    },
    {
        key: "ea2010_s136",
        title: "Equality Act 2010, section 136 (burden of proof)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2010/15/section/136",
        reference: "EA 2010 s136",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        effectiveFrom: "2010-10-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["If there are facts from which discrimination could be concluded, the employer must show it did not discriminate."],
        version: "1",
    },
    {
        key: "era2025_fire_and_rehire",
        title: "Employment Rights Act 2025 — dismissal for refusing a contract variation (automatically unfair)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2025/36/contents",
        reference: "ERA 2025 (fire-and-rehire provisions)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        publishedDate: ERA_2025.ROYAL_ASSENT,
        effectiveFrom: ERA_2025.FIRE_AND_REHIRE_AUTO_UNFAIR,
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Applies to dismissals with an effective date of termination on or after commencement; limited financial-distress exception.", "Stored date 1 January 2027; commencement instrument not yet verified (see register)."],
        commencementConfirmed: isRuleCommenced("FIRE_AND_REHIRE_AUTO_UNFAIR"),
        version: "1",
    },
    {
        key: "era2025_zero_hours",
        title: "Employment Rights Act 2025 — zero-hours and low-hours workers (guaranteed hours, shift notice, cancellation payments)",
        publisher: "legislation.gov.uk",
        url: "https://www.legislation.gov.uk/ukpga/2025/36/contents",
        reference: "ERA 2025 (zero-hours provisions)",
        jurisdiction: ["great_britain"],
        sourceType: "legislation",
        publishedDate: ERA_2025.ROYAL_ASSENT,
        effectiveFrom: "2099-01-01",
        effectiveTo: null,
        lastVerifiedAt: PRIOR_REVIEW,
        verification: NOT_RECHECKED,
        applicability: ["Not yet in force. Exact commencement date to be confirmed by Statutory Instrument; the effectiveFrom placeholder prevents accidental application."],
        commencementConfirmed: false,
        version: "1",
    },
];

const byKey = new Map(LEGAL_SOURCES.map((s) => [s.key, s]));

export function getSource(key: string): LegalSource {
    const s = byKey.get(key);
    if (!s) throw new Error(`Unknown legal source key: ${key}`);
    return s;
}

export function hasSource(key: string): boolean {
    return byKey.has(key);
}

/** The version of a source family in force on a given date, or null. */
export function applicableSource(key: string, eventDate: string): LegalSource | null {
    const s = byKey.get(key);
    if (!s) return null;
    if (eventDate < s.effectiveFrom) return null;
    if (s.effectiveTo && eventDate > s.effectiveTo) return null;
    return s;
}

export function citeSource(key: string): { key: string; title: string; reference: string; url: string; version: string } {
    const s = getSource(key);
    return { key: s.key, title: s.title, reference: s.reference, url: s.url, version: s.version };
}
