/**
 * Artifact policy — the ONE place that says, for each artifact type, which
 * regulatory flags must be on, which entitlement tier is needed, whether the
 * model drafts it at all, and whether the generic `generateArtifact` path may
 * produce it.
 *
 * `assertArtifactAllowed` is called first thing in `generateArtifact` (before
 * any usage counting or model call). Flags are applied before entitlement so
 * a disabled feature is a 404 (`feature_disabled`) regardless of what the
 * user has paid for. Pricing copy and the capabilities endpoint read the same
 * flags so nothing is sold that this table refuses.
 */

import { ARTIFACT_TYPES, type ArtifactType, type EntitlementTier } from "@/db/enums";
import { type FlagName } from "@/flags";
import { requireFlag } from "@/flags/guard";
import { ValidationError } from "@/lib/errors";
import type { Actor } from "@/cases/access";
import { requireEntitlement } from "@/entitlements/service";

export interface ArtifactPolicy {
    /** Entitlement tier required when payments are on; null = never paywalled. */
    tier: EntitlementTier | null;
    /** Every listed flag must be on. */
    flags: FlagName[];
    /** False = assembled deterministically from the record (no model call). */
    modelDrafted: boolean;
    /** False = `generateArtifact` refuses this type; a dedicated path serves it. */
    allowedViaGenericGeneration: boolean;
    note: string;
}

export const ARTIFACT_POLICY: Record<ArtifactType, ArtifactPolicy> = {
    grievance_letter: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Drafted from confirmed facts and the grievance process record." },
    grievance_appeal: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Drafted from confirmed facts and the selected appeal grounds." },
    disciplinary_response: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Hearing preparation from allegations and the worker's recorded responses." },
    disciplinary_appeal: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Drafted from confirmed facts and the selected appeal grounds." },
    chronology: { tier: "case_pass", flags: [], modelDrafted: false, allowedViaGenericGeneration: true, note: "Rendered deterministically from confirmed events; no model call." },
    case_summary: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Neutral summary of confirmed material." },
    acas_preparation: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Early Conciliation preparation note; cites the Acas EC guidance source." },
    meeting_preparation: { tier: "case_pass", flags: [], modelDrafted: true, allowedViaGenericGeneration: true, note: "Meeting notes from confirmed facts." },
    potential_claims_summary: {
        tier: "claim_pack",
        flags: ["ENABLE_PERSONALISED_CLAIM_IDENTIFICATION"],
        modelDrafted: true,
        allowedViaGenericGeneration: true,
        note: "Personalised possible-claim wording. Regulatory flag enforced server-side; 404 when off.",
    },
    et1_readiness_pack: {
        tier: "claim_pack",
        flags: ["ENABLE_PERSONALISED_ET1_DRAFTING"],
        modelDrafted: true,
        allowedViaGenericGeneration: true,
        note: "Model-drafted ET1 wording via generateArtifact needs the ET1 drafting flag. The deterministic readiness pack (src/et1/service.ts saveEt1PackArtifact) is a separate path and is NOT gated by this flag.",
    },
    case_pack: {
        tier: "claim_pack",
        flags: [],
        modelDrafted: false,
        allowedViaGenericGeneration: false,
        note: "Never model-generated. Served by the deterministic export (GET /api/cases/:id/export).",
    },
};

export function isKnownArtifactType(type: unknown): type is ArtifactType {
    return typeof type === "string" && (ARTIFACT_TYPES as readonly string[]).includes(type);
}

/** Tier required for an artifact type (null = never paywalled). */
export function policyTierForArtifact(type: ArtifactType): EntitlementTier | null {
    return ARTIFACT_POLICY[type].tier;
}

/**
 * Refuse generation that policy does not permit. Order: type validity →
 * generic-path allowed → flags (404 feature_disabled) → entitlement (402).
 * Throws before anything is counted, drafted or written.
 */
export async function assertArtifactAllowed(actor: Actor, caseId: string, type: unknown): Promise<ArtifactPolicy> {
    if (!isKnownArtifactType(type)) throw new ValidationError("Unknown document type.");
    const policy = ARTIFACT_POLICY[type];
    if (!policy.allowedViaGenericGeneration) {
        throw new ValidationError(`The ${type.replace(/_/g, " ")} is not generated by drafting. Use the case export (/api/cases/${caseId}/export) instead.`);
    }
    for (const flag of policy.flags) requireFlag(flag);
    if (policy.tier) await requireEntitlement(actor, caseId, policy.tier);
    return policy;
}
