/**
 * Generated artifacts — letters, chronologies, summaries, preparation notes.
 *
 * Case facts and generated wording are different things. An artifact records
 * the basis it was generated from (fact/event/document ids and a hash of
 * their content). Editing the wording never changes facts; changing facts
 * marks the artifact stale so the user can regenerate it.
 *
 * Chronology and case summary are built deterministically from confirmed
 * events. Letters and preparation notes use the drafting task; the mock
 * provider produces a faithful template so tests are hermetic.
 */

import { createHash } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db/client";
import { artifacts, ARTIFACT_TYPES, type ArtifactBasis, type ArtifactType, type GrievanceProcessData } from "@/db/schema";
import { newId } from "@/lib/ids";
import { ValidationError } from "@/lib/errors";
import { requireCaseAccess, touchCase, type Actor } from "@/cases/access";
import { recordAudit } from "@/cases/audit";
import { getEmployment, listPersons } from "@/cases/service";
import { listConfirmedEvents } from "@/timeline/service";
import { listConfirmedFacts } from "@/facts/service";
import { listDocuments } from "@/documents/service";
import { listIssues } from "@/issues/service";
import { getProcess, listAllegations, listAppealGrounds } from "@/processes/service";
import { getProvider } from "@/ai/routing";
import { runDraft } from "@/ai/tasks/draft";
import { checkAndCountUsage } from "@/entitlements/fair-use";
import { requireEntitlementForArtifact } from "@/entitlements/service";
import { formatLongDate } from "@/lib/dates";
import { BRAND, LEGAL_INFORMATION_DISCLAIMER } from "@/brand/config";

export type ArtifactRow = typeof artifacts.$inferSelect;

const TITLES: Record<ArtifactType, string> = {
    grievance_letter: "Grievance letter",
    grievance_appeal: "Grievance appeal",
    disciplinary_response: "Disciplinary hearing preparation",
    disciplinary_appeal: "Disciplinary appeal",
    chronology: "Chronology",
    case_summary: "Case summary",
    acas_preparation: "Acas Early Conciliation preparation",
    meeting_preparation: "Meeting preparation",
    potential_claims_summary: "Possible claims summary",
    et1_readiness_pack: "ET1 readiness pack",
    case_pack: "Case pack",
};

function hashInputs(parts: unknown[]): string {
    return createHash("sha256").update(JSON.stringify(parts)).digest("hex").slice(0, 32);
}

async function gatherBasis(actor: Actor, caseId: string, processId?: string | null) {
    const events = await listConfirmedEvents(caseId);
    const facts = await listConfirmedFacts(caseId);
    const docs = await listDocuments(actor, caseId);
    const employment = await getEmployment(actor, caseId);
    const people = await listPersons(actor, caseId);
    const issues = await listIssues(actor, caseId);
    const basis: ArtifactBasis = {
        factIds: facts.map((f) => f.id),
        eventIds: events.map((e) => e.id),
        documentIds: docs.map((d) => d.id),
        processId: processId ?? undefined,
        inputsHash: hashInputs([
            events.map((e) => [e.id, e.date, e.title, e.description]),
            facts.map((f) => [f.id, f.statement, f.value]),
            docs.map((d) => [d.id, d.docType, d.docDate]),
            employment,
            issues.map((i) => [i.id, i.title, i.description, i.desiredResolution]),
        ]),
    };
    return { events, facts, docs, employment, people, issues, basis };
}

export function renderChronology(events: Array<{ date: string; dateEnd: string | null; dateApproximate: boolean; title: string; description: string | null; category: string; disputed: boolean; sourceDocumentIds: string[] }>, docs: Array<{ id: string; filename: string }>): string {
    const lines = ["# Chronology", "", "_Confirmed events only, in date order. Approximate dates are marked._", ""];
    if (events.length === 0) lines.push("_No events have been confirmed yet._");
    const docName = new Map(docs.map((d) => [d.id, d.filename]));
    for (const e of events) {
        const when = `${formatLongDate(e.date)}${e.dateEnd ? ` to ${formatLongDate(e.dateEnd)}` : ""}${e.dateApproximate ? " (approximate)" : ""}`;
        lines.push(`## ${when} — ${e.title}${e.disputed ? " (disputed)" : ""}`);
        if (e.description && e.description !== e.title) lines.push("", e.description);
        const sources = e.sourceDocumentIds.map((id) => docName.get(id)).filter(Boolean);
        if (sources.length) lines.push("", `_Documents: ${sources.join(", ")}_`);
        lines.push("");
    }
    lines.push(`_Generated by ${BRAND.name} from the confirmed case record. ${LEGAL_INFORMATION_DISCLAIMER}_`);
    return lines.join("\n");
}

export async function generateArtifact(actor: Actor, caseId: string, type: ArtifactType, opts?: { processId?: string | null; extra?: Record<string, unknown> }): Promise<ArtifactRow> {
    if (!(ARTIFACT_TYPES as readonly string[]).includes(type)) throw new ValidationError("Unknown document type.");
    const c = await requireCaseAccess(actor, caseId);
    await requireEntitlementForArtifact(actor, caseId, type);
    const { events, facts, docs, employment, people, issues, basis } = await gatherBasis(actor, caseId, opts?.processId);

    let content: string;
    let generatedBy = "system";

    if (type === "chronology") {
        content = renderChronology(events, docs);
    } else {
        const usage = await checkAndCountUsage(actor.userId, caseId, "ai_generation");
        if (!usage.ok) throw new ValidationError(usage.reason);
        const payload: Record<string, unknown> = {
            title: TITLES[type],
            employer: employment.employerName ?? "[employer name]",
            jobTitle: employment.jobTitle ?? null,
            people: people.map((p) => ({ name: p.name, role: p.role })),
            issues: issues.map((i) => ({ title: i.title, description: i.description, desiredResolution: i.desiredResolution })),
            events: events.map((e) => ({ date: e.date, approximate: e.dateApproximate, title: e.title, description: e.description, disputed: e.disputed })),
            facts: facts.map((f) => ({ statement: f.statement, provenance: f.provenance, disputed: f.disputed })),
            documents: docs.map((d) => ({ filename: d.filename, type: d.docType, date: d.docDate })),
            desiredResolution: issues.map((i) => i.desiredResolution).filter(Boolean).join("; ") || null,
            uncertainties: [
                ...(employment.employerName ? [] : ["Employer name not recorded."]),
                ...facts.filter((f) => f.disputed).map((f) => `Disputed: ${f.statement}`),
            ],
            ...(opts?.extra ?? {}),
        };
        if (opts?.processId) {
            const proc = await getProcess(actor, caseId, opts.processId);
            payload.process = { type: proc.type, state: proc.state, data: proc.data };
            if (proc.type === "disciplinary") {
                payload.allegations = (await listAllegations(actor, caseId, proc.id)).map((a) => ({ employerAllegation: a.employerAllegation, employerEvidence: a.employerEvidence, workerResponse: a.workerResponse, workerEvidence: a.workerEvidence, missingInformation: a.missingInformation, hearingQuestions: a.hearingQuestions }));
            }
            if (proc.type === "grievance") {
                const gd = proc.data as GrievanceProcessData;
                if (gd.desiredResolution) payload.desiredResolution = gd.desiredResolution;
            }
            if (proc.type === "grievance_appeal" || proc.type === "disciplinary_appeal" || type === "grievance_appeal" || type === "disciplinary_appeal") {
                payload.grounds = (await listAppealGrounds(actor, caseId, proc.id)).filter((g) => g.selected).map((g) => ({ category: g.category, summary: g.summary, detail: g.detail }));
            }
        }
        const provider = await getProvider();
        const draft = await runDraft(provider, type, payload);
        content = `${draft.text.trim()}\n\n---\n_${LEGAL_INFORMATION_DISCLAIMER}_`;
        generatedBy = `${draft.provider}:${draft.model}`;
    }

    const db = await getDb();
    const existing = await db.select().from(artifacts).where(and(eq(artifacts.caseId, caseId), eq(artifacts.type, type), opts?.processId ? eq(artifacts.processId, opts.processId) : eq(artifacts.status, "draft"))).orderBy(desc(artifacts.version)).limit(1);
    const version = (existing[0]?.version ?? 0) + 1;
    const id = newId();
    await db.insert(artifacts).values({ id, caseId, type, title: TITLES[type], content, version, status: "draft", stale: false, basis, processId: opts?.processId ?? null, generatedBy });
    await touchCase(caseId);
    await recordAudit({ userId: actor.userId, caseId, action: "artifact.generated", targetType: "artifact", targetId: id, details: { type, version, generatedBy, events: events.length, facts: facts.length, jurisdiction: c.jurisdiction } });
    return (await db.select().from(artifacts).where(eq(artifacts.id, id)))[0];
}

export async function listArtifacts(actor: Actor, caseId: string): Promise<ArtifactRow[]> {
    await requireCaseAccess(actor, caseId);
    const db = await getDb();
    return db.select().from(artifacts).where(eq(artifacts.caseId, caseId)).orderBy(desc(artifacts.updatedAt));
}

export async function getArtifact(actor: Actor, caseId: string, artifactId: string): Promise<ArtifactRow> {
    await requireCaseAccess(actor, caseId);
    const db = await getDb();
    const rows = await db.select().from(artifacts).where(and(eq(artifacts.id, artifactId), eq(artifacts.caseId, caseId))).limit(1);
    if (!rows[0]) throw new ValidationError("Document not found.");
    return rows[0];
}

/** Edit wording. Never touches facts. */
export async function editArtifact(actor: Actor, caseId: string, artifactId: string, patch: { content?: string; title?: string; status?: "draft" | "final" }): Promise<ArtifactRow> {
    await getArtifact(actor, caseId, artifactId);
    if (patch.content !== undefined && patch.content.length > 200_000) throw new ValidationError("The document is too long.");
    const db = await getDb();
    await db.update(artifacts).set({ ...patch, updatedAt: new Date() }).where(eq(artifacts.id, artifactId));
    await touchCase(caseId);
    await recordAudit({ userId: actor.userId, caseId, action: "artifact.edited", targetType: "artifact", targetId: artifactId, details: { fields: Object.keys(patch) } });
    return getArtifact(actor, caseId, artifactId);
}

export async function deleteArtifact(actor: Actor, caseId: string, artifactId: string): Promise<void> {
    await getArtifact(actor, caseId, artifactId);
    const db = await getDb();
    await db.delete(artifacts).where(eq(artifacts.id, artifactId));
}

/** Recompute staleness by comparing the stored inputs hash with the current basis. */
export async function refreshArtifactStaleness(actor: Actor, caseId: string): Promise<void> {
    const { basis } = await gatherBasis(actor, caseId);
    const db = await getDb();
    const rows = await db.select().from(artifacts).where(eq(artifacts.caseId, caseId));
    for (const r of rows) {
        if (r.type === "chronology" || r.type === "case_summary") {
            const stale = r.basis.inputsHash !== basis.inputsHash;
            if (stale !== r.stale) await db.update(artifacts).set({ stale, staleReason: stale ? "the case record changed since this was generated" : null }).where(eq(artifacts.id, r.id));
        }
    }
}
